#!/usr/bin/env bash

# Set up autograder files
cd /autograder/source

find /autograder/submission -iname "*.xlsx" -exec cp "{}" ./submission.xlsx \;
find /autograder/submission -iname "*.txt" -exec cp "{}" ./tronview.txt \;
python3 autograder.py
